name: Accessibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        wordpress: [latest, '6.3', '6.2']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, mysql
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup WordPress
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}
        
    - name: Run PHPUnit Accessibility Tests
      run: composer test tests/accessibility/test-accessibility.php

    - name: Start WordPress Server
      run: |
        php -S localhost:8080 &
        sleep 5

    - name: Run Pa11y Tests
      run: npm run test:a11y
      
    - name: Run Axe Tests
      run: npm run test:axe

    - name: Run Lighthouse Accessibility Audit
      run: npm run audit:a11y
      
    - name: Upload Accessibility Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: accessibility-reports-${{ matrix.php }}-wp-${{ matrix.wordpress }}
        path: |
          pa11y-results/
          lighthouse-results/
          test-results/
        retention-days: 14

  report:
    needs: accessibility
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Generate Summary Report
      run: |
        echo "# Accessibility Test Results" > $GITHUB_STEP_SUMMARY
        echo "## Test Matrix Results" >> $GITHUB_STEP_SUMMARY
        for dir in accessibility-reports-*; do
          echo "### $dir" >> $GITHUB_STEP_SUMMARY
          if [ -f "$dir/pa11y-results/summary.json" ]; then
            echo "#### Pa11y Results" >> $GITHUB_STEP_SUMMARY
            cat "$dir/pa11y-results/summary.json" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "$dir/lighthouse-results/accessibility.json" ]; then
            echo "#### Lighthouse Results" >> $GITHUB_STEP_SUMMARY
            cat "$dir/lighthouse-results/accessibility.json" >> $GITHUB_STEP_SUMMARY
          fi
        done

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.name,
            title: 'Accessibility Test Failures',
            body: 'Accessibility tests failed in workflow run: ' + context.serverUrl + '/' + context.repo.owner + '/' + context.repo.name + '/actions/runs/' + context.runId
          })
